# Generated by Django 4.1.4 on 2022-12-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KdaList',
            fields=[
                ('time', models.AutoField(primary_key=True, serialize=False)),
                ('kda', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('aii_kill', models.IntegerField()),
                ('eii_kill', models.IntegerField()),
                ('category', models.TextField()),
                ('match_id', models.IntegerField()),
            ],
            options={
                'db_table': 'kda_list',
            },
        ),
    ]
