# Generated by Django 4.1.4 on 2022-12-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('nickname', models.AutoField(primary_key=True, serialize=False)),
                ('puuid', models.UUIDField()),
            ],
            options={
                'db_table': 'play_users',
            },
        ),
    ]
