# Generated by Django 4.1.4 on 2022-12-10 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('minimap_ward', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinOutput',
            fields=[
                ('ward_place', models.AutoField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('minimap_ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minimap_ward.minimapward')),
            ],
            options={
                'db_table': 'min_output',
            },
        ),
    ]
