# Generated by Django 4.1.4 on 2022-12-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinimapWard',
            fields=[
                ('time', models.AutoField(primary_key=True, serialize=False)),
                ('team', models.IntegerField()),
                ('ward_place', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('champion_count', models.IntegerField()),
                ('ward_type', models.IntegerField()),
                ('control_count', models.IntegerField()),
                ('ward_duration', models.IntegerField()),
            ],
            options={
                'db_table': 'minimap_ward',
            },
        ),
    ]
